services:
  redis:
    ports: !override
      - "16379:6379"

  mysql:
    ports: !override
      - "13306:3306"
    volumes:
      - ./data-dev/mysql:/var/lib/mysql
      - ./docker-add-file/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf

  frontend:
    ports: !override
      - "18080:80"

#启动/停止命令：
 #到docker文件夹下面：  cd ~/projects/mlops/install/docker/
 # 启动：docker compose -f docker-compose.yml -f docker-compose.dev.yml -p zhaohongkai up -d
 #docker exec -it zhaohongkai-myapp-1 bash
 #/entrypoint.sh或python myapp/run.py
 # 停止：docker compose -f docker-compose.yml -f docker-compose.dev.yml -p zhaohongkai down

 # 连接远程开发服务器命令：
 #ssh stu04@10.121.177.229   密码111111

#网页地址是： http://10.121.177.229:18777
  
  # 克隆代码

  # cd ~/projects
  # git clone -b hk ssh://git@10.121.177.103:8222/mlops/mlops.git