# 训练调用需要
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-kubeflow-global-pv-juicefs
  labels:
    pipeline-pvname: pipeline-kubeflow-global-pv-juicefs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: juicefs-sc
  csi:
    driver: csi.juicefs.com
    volumeHandle: pipeline-kubeflow-global-pv-juicefs
    fsType: juicefs
    nodePublishSecretRef:
      name: juicefs-sc-secret
      namespace: kube-system
    volumeAttributes:
      juicefs/mount-cpu-limit: 5000m
      juicefs/mount-memory-limit: 5Gi
      juicefs/mount-cpu-request: 1m
      juicefs/mount-memory-request: 1Mi
  mountOptions:
    - subdir=kubeflow/global
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubeflow-global-pvc-juicefs
  namespace: pipeline
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
#  selector:
#    matchLabels:
#      pipeline-pvname: pipeline-kubeflow-global-pv
  storageClassName: juicefs-sc
  volumeName: pipeline-kubeflow-global-pv-juicefs

# 模型训练
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-kubeflow-user-workspace-juicefs
  labels:
    pipeline-pvname: pipeline-kubeflow-user-workspace-juicefs
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: juicefs-sc
  csi:
    driver: csi.juicefs.com
    volumeHandle: pipeline-kubeflow-user-workspace-juicefs
    fsType: juicefs
    nodePublishSecretRef:
      name: juicefs-sc-secret
      namespace: kube-system
    volumeAttributes:
      juicefs/mount-cpu-limit: 5000m
      juicefs/mount-memory-limit: 5Gi
      juicefs/mount-cpu-request: 1m
      juicefs/mount-memory-request: 1Mi
  mountOptions:
    - subdir=kubeflow/pipeline/workspace
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubeflow-user-workspace-juicefs
  namespace: pipeline
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
#  selector:
#    matchLabels:
#      pipeline-pvname: pipeline-kubeflow-user-workspace
  storageClassName: juicefs-sc
  volumeName: pipeline-kubeflow-user-workspace-juicefs
# 模型归档
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-kubeflow-archives-juicefs
  labels:
    pipeline-pvname: pipeline-kubeflow-archives-juicefs
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: juicefs-sc
  csi:
    driver: csi.juicefs.com
    volumeHandle: pipeline-kubeflow-archives-juicefs
    fsType: juicefs
    nodePublishSecretRef:
      name: juicefs-sc-secret
      namespace: kube-system
    volumeAttributes:
      juicefs/mount-cpu-limit: 5000m
      juicefs/mount-memory-limit: 5Gi
      juicefs/mount-cpu-request: 1m
      juicefs/mount-memory-request: 1Mi
  mountOptions:
    - subdir=kubeflow/pipeline/archives
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubeflow-archives-juicefs
  namespace: pipeline
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
#  selector:
#    matchLabels:
#      pipeline-pvname: pipeline-kubeflow-archives
  storageClassName: juicefs-sc
  volumeName: pipeline-kubeflow-archives-juicefs